<?php if (count($this->rowsetRelatedItem) > 0) { ?>
<table border="0" width="100%" cellpadding="0" cellspacing="0">
<tr>
	<td class="widgetHeader">
	<table width="100%">
	<tr>
		<td scope="col" height="20" colspan="2"><div class="widgetHeaderTitle">Nama Dokumen</div></td>
		<td scope="col"><div class="widgetHeaderTitle">Ukuran</div></td>
	</tr>
	</table>
	</td>
</tr>
<tr>
	<td>
	<div class="widgetContent">
	<div style="padding-top:5px"></div>
	<table>
	<?php foreach ($this->rowsetRelatedItem as $row){?>
	<tr valign="top">	
		<td><?php echo $this->GetCatalogDocType($row->itemGuid); ?></td>
		<td width="460"><a href="<?php echo $this->getKutuRootUrl();?>/download/<?php echo $row->itemGuid;?>/parent/<?php echo $row->relatedGuid;?>" class="linkhref"><?php echo $this->getCatalogTitle($row->itemGuid); ?></a></td>
		<td><div style="color: #333333;font-size: 11px;font-family: verdana,arial,helvetica,sans-serif;"><?php echo $this->GetCatalogDocSize($row->itemGuid); ?></div></td>
		
	</tr>	
	<?php } ?>
	</table>
	<div style="padding-top:5px"></div>
	</div>
	</td>
</tr>
</table>
<?php } ?> 

