<?php if (count($this->aData) > 0) { ?>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
	<td class="widgetHeader">
	<table>
	<tr>
		<td width="100%"><div class="widgetHeaderTitle">Sejarah</div></td>
	</tr>
	</table>
	</td>
</tr>
<tr>
	<td>
	<div class="widgetContent">
	<?php foreach ($this->aData as $data){?>
		<div style="padding-top:5px"></div>
		<?php if($data['node']==$this->catalogGuid) {?><img src="<?php echo $this->getKutuRootUrl(); ?>/resources/img/resultset_next.png"><?php } ?>
		<a href="<?php echo $this->getKutuRootUrl();?>/detail/<?php echo $data['node'];?>/node/<?php echo $this->node; ?>" class="linkhref"><?php echo $data['title']; ?></a>
		<br><div style="color: #333333;font-size: 11px;font-family: verdana,arial,helvetica,sans-serif;"><?php echo $data['subTitle']; ?></div>
		<?php if ($data['description']) { ?><div style="color: #333333;font-size: 11px;font-family: verdana,arial,helvetica,sans-serif;"><strong>Catatan: </strong><?php echo $data['description']; ?></div><?php } ?>
		<div style="padding-top:5px"></div>
	<?php }?>
	</div>
	</td>
</tr>
</table>
<?php } ?>